- dbt/adapters/spark/connections.py
Fix the error check reported by @jtcohen6
> fix error check

- README.md
- setup.py
- update readme
- tweak setup.py descriptions
> prep release for 0.13.0

- setup.py
resolves https://github.com/fishtown-analytics/dbt/issues/2147
> freeze jinja2 version to resolve `._compat` issue

- README.md
> Add header and badge

- dbt/adapters/spark/connections.py
I was a little too eager when merging #106 :)
I'm going to amend our Circle settings for dbt-spark + dbt-presto to run integration tests for PRs from forks as well.
> Fix unit tests

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
- CHANGELOG.md
> Add changelog, issue templates

- .bumpversion-dbt.cfg
- dbt/adapters/spark/__version__.py
- dbt/adapters/spark/connections.py
- dbt/include/spark/macros/materializations/seed.sql
- dbt/include/spark/macros/materializations/snapshot.sql
- dev_requirements.txt
- requirements.txt
- setup.py
- test/unit/test_adapter.py
resolves #136 
- bump dbt to 0.19.0rc1
- apply updates for new dbt API (notably `get_status` -> `get_response`)
- update `pytest-dbt-adapter` to handle artifact changes in dbt 0.19*
> bump to 0.19.0rc1

- dbt/include/spark/sample_profiles.yml
The odbc endpoint has been added, but this isn't reflected in the sample.
resolves #
> Update to the latest version

- CHANGELOG.md
- dbt/include/spark/macros/materializations/seed.sql
- test/custom/seed_column_types/data/payments.csv
- test/custom/seed_column_types/test_seed_column_types.py
> Explicitly cast column types when inserting into seeds

- .bumpversion-dbt.cfg
- .bumpversion.cfg
- dbt/adapters/spark/__version__.py
- requirements.txt
- setup.py
resolves #173
Bump version to 0.19.2rc2 to match dbt Core.
> Bump version to 0.19.2rc2

- CHANGELOG.md
- README.md
- dbt/adapters/spark/connections.py
> Backport PR #194

- .github/workflows/release.yml
> Bump version to 0.21.1rc1

- CHANGELOG.md
- dbt/include/spark/macros/materializations/seed.sql
resolves #249
- ~I have run this code in development and it appears to resolve the stated issue~
- ~This PR includes tests, or tests are not required/relevant for this PR~
> Refactor seed macros, clearer sql param logging

- .github/workflows/release.yml
> Bump version to 1.0.0

- setup.py
Temp fix for package version naming
> Fix version for package

- CHANGELOG.md
- dbt/adapters/spark/connections.py
resolves #280
Closes the connection properly.
> Closes the connection properly.

- README.md
resolves #
Bring back local spark instruction
> bring back local instruction

- tests/integration/incremental_strategies/models_insert_overwrite/insert_overwrite_no_partitions.sql
Backport #301 to fix failing tests
> Configure insert_overwrite models to use parquet (#301)

- .github/workflows/version-bump.yml
Backport #303 to fix the version bump Action
> Add sasl dependency (#303)

- dbt/adapters/spark/impl.py
- tests/functional/adapter/test_basic.py
convert adapter method test and normalize behavior of get_columns_in_relation behavior to return empty list when relation doesn't exist
> convert adapter test

- .bumpversion.cfg
- .github/workflows/main.yml
- CHANGELOG.md
- dbt/adapters/spark/__version__.py
- dbt/adapters/spark/impl.py
- setup.py
> catch table or view not exist error in spark 3.0+

- .bumpversion.cfg
- .github/workflows/main.yml
- CHANGELOG.md
- dbt/adapters/spark/__version__.py
- dbt/adapters/spark/impl.py
- setup.py
> Backport table not exist, Bumping version to 1.1.0rc1

- CHANGELOG.md
Fixed the version update for the Spark upgrade in the CHANGELOG
> Fix changelog for spark upgrade feature

- .github/workflows/main.yml
> Updating CI pip and py10 (#403)

- CHANGELOG.md
- dbt/include/spark/macros/materializations/incremental/incremental.sql
resolves #402
This makes a minor change to allow this adapter to work with the dbt core incremental materialization refactor.
> Change to support core incremental refactor

- .changes/unreleased/Under the Hood-20220825-073413.yaml
- dbt/include/spark/macros/materializations/incremental/incremental.sql
- dbt/include/spark/macros/materializations/table.sql
> add supported language

- .changes/unreleased/Under the Hood-20220913-152004.yaml
- dbt/adapters/spark/__init__.py
- dbt/adapters/spark/column.py
- dbt/adapters/spark/connections.py
- dbt/adapters/spark/impl.py
> add mypy ignore to column, connections and init

- .github/workflows/bot-changelog.yml
resolves: #465 
Copy changes made to the changebot to fix trigger issue documented here https://github.com/dbt-labs/dbt-core/pull/5754
> Update changelog bot

- dev-requirements.txt
resolves #1243
Previous pull request didn't remove branch reference
> Remove branch ref from dev-requirements.txt

- .changes/unreleased/Under the Hood-20220924-143713.yaml
- dbt/include/spark/macros/materializations/table.sql
- dev-requirements.txt
resolves #473
related to https://github.com/dbt-labs/dbt-bigquery/pull/321 and https://github.com/dbt-labs/dbt-core/pull/5928
Convert df to pyspark DataFrame if it is koalas before writing.
- https://github.com/dbt-labs/dbt-core/pull/5928
- https://github.com/dbt-labs/dbt-bigquery/pull/321
- https://github.com/dbt-labs/dbt-spark/pull/474 (this one)
> Convert df to pyspark DataFrame if it is koalas before writing

- dbt/adapters/spark/python_submissions.py
- dbt/include/spark/macros/materializations/table.sql
- tests/functional/adapter/test_python_model.py
- tox.ini
resolves #
Allow configure package, fix cluster_id, fix type check for older version of databricks image
> rc bug fix

- .github/workflows/main.yml
resolves #https://github.com/dbt-labs/dbt-core/issues/6203
Upgrade actions/setup-python from v2 to v4.3.0 to bring in all the updates for deprecations
Defines Python Version to use when installing dependencies
> [CT-1469] init pr for short term python version issue fix

- .github/workflows/main.yml
resolves #https://github.com/dbt-labs/dbt-core/issues/6203
Upgrade actions/setup-python from v2 to v4.3.0 to bring in all the updates for deprecations
Defines Python Version to use when installing dependencies
> [Backport][CT-1469] pr for short term python version issue fix

- .changes/unreleased/Fixes-20221113-211208.yaml
- README.md
> [CT-1486]dbt run fails with spark-testing profile of examples

- .github/workflows/main.yml
resolves # https://github.com/dbt-labs/dbt-core/issues/6203 and #511
manual backport of #511 because 1.1.latest was missing some minor changes in other prs that needed to be merged first
> [Backport] [CT-1469] manual pr for short term python version issue fix

- .changes/unreleased/Fixes-20221116-234601.yaml
- dbt/adapters/spark/impl.py
resolves #515 
manual backport of #520 to 1.3.latest
> [BACKPORT] Supports new error messages. (#520)

- .changes/unreleased/Fixes-20221116-234601.yaml
- dbt/adapters/spark/impl.py
resolves #515 
manual backport of https://github.com/dbt-labs/dbt-spark/pull/520 with slight modification to make more relevant to state of 1.1.latest.
> [BACKPORT ]manual backport/modifcation of #520 to 1.1.latest

- .changes/unreleased/Under the Hood-20221202-140724.yaml
- setup.py
- tox.ini
resolves #534 
manual backport of #534 to fix issue with tox on unit tests
> [BACKPORT]  pr #534 to 1.1.latest

- .circleci/config.yml
> add context var for aws creds

- .changie.yaml
resolves #548, extension of #603
More testing showed input type is int which will block entering multiple issues on a single changie yaml.
> change type to string

- .bumpversion.cfg
- .github/workflows/release.yml
resolves # N/A
This PR is just a backport of the following commits:
- #592
- #613
> [CI/CD] Backport release workflow to `1.4.latest`

- .bumpversion.cfg
- .github/workflows/release.yml
resolves # N/A
This PR is just a backport of the following commits:
- #592
- #613
> [CI/CD] Backport release workflow to `1.3.latest`

- .bumpversion.cfg
- .github/workflows/release.yml
resolves # N/A
This PR is just a backport of the following commits:
- #592
- #613
> [CI/CD] Backport release workflow to `1.1.latest`

- .bumpversion.cfg
- .github/workflows/release.yml
resolves # N/A
This PR is just a backport of the following commits:
- #592
- #613
> [CI/CD] Backport release workflow to `1.2.latest`

- .changes/unreleased/Under the Hood-20230223-105838.yaml
- dbt/include/spark/macros/adapters.sql
resolves #645
Rename "constraints_enabled" to "contract"
> Rename constraints_enabled to contract

- .github/workflows/jira-creation.yml
- .github/workflows/jira-label.yml
- .github/workflows/jira-transition.yml
matching logic from https://github.com/dbt-labs/dbt-snowflake/pull/460
> mirror issues to ADAP jira project

- README.md
Update the status badge on the README.md to use the CircleCI status.
> update integration test badge to use circleci

- dbt/adapters/spark/impl.py
Convert relation to a string for logs
> stringify relation

- .github/workflows/main.yml
resolves #740 
Backport to 1.1.latest. Does not require a patch release since this is only around testing automation.
> [Backport] 1.1.latest gh deprecations

- .github/workflows/main.yml
resolves #740 
Backport to 1.5.latest. Does not require a patch release since this is only around testing automation.
> [Backport] 1.5.latest gh deprecations

- .github/workflows/main.yml
resolves #740 
Backport to 1.3.latest. Does not require a patch release since this is only around testing automation.
> [Backport] 1.3.latest gh deprecations

- .changes/0.0.0.md
- CHANGELOG.md
resolves #
adding link to 1.5.latest changelog
> adding link to 1.5 release notes

- dev-requirements.txt
> revert change to dev-requirements.txt

- .changes/unreleased/Under the Hood-20230830-160616.yaml
- dbt/adapters/spark/column.py
- dbt/adapters/spark/connections.py
> remove holograms and supply defaults/validation logic

- .github/workflows/docs-issues.yml
resolves #https://github.com/dbt-labs/actions/issues/111
Overlooking docs changes related to `dbt-core` and adapters changes
Automate the creation of docs issues by adding the `user docs` a label to merged PRs
> add docs-issue workflow to dbt-spark

- dagger/run_dbt_spark_tests.py
> fix ODBC_DRIVER env var

- .changes/unreleased/Under the Hood-20240410-183535.yaml
- .github/dependabot.yml
We have inconsistent and under-configured dependabot config files.
Consistify them.
> Update dependabot config to cover GHA and Docker

- .github/workflows/main.yml
> [Backport 1.0.latest] Pin `macos` runners to `macos-12` (#1016)

- .github/workflows/main.yml
> [Backport 1.1.latest] Swap the order of the sdist and wheel checks (#1065)

- .github/workflows/main.yml
> [Backport 1.0.latest] Swap the order of the sdist and wheel checks (#1065)

- .github/workflows/main.yml
> [Backport 1.2.latest] Swap the order of the sdist and wheel checks (#1065)

- dagger/spark-container/install_spark.sh
- docker/spark.Dockerfile
resolves #
https://github.com/dbt-labs/dbt-spark/actions/runs/10130000586/job/28010724196?pr=1081
specify netcat install type
> update netcat install method to fix ci/cd

- .changes/unreleased/Breaking Changes-20241016-184157.yaml
- .github/workflows/main.yml
- .pre-commit-config.yaml
- CONTRIBUTING.md
- Makefile
- setup.py
- tox.ini
> [Backport 1.4.latest] Drop support for Python 3.8

- .changes/unreleased/Breaking Changes-20241016-184157.yaml
- .github/workflows/main.yml
- .pre-commit-config.yaml
- CONTRIBUTING.md
- Makefile
- setup.py
- tox.ini
> [Backport 1.5.latest] Drop support for Python 3.8

- .changes/unreleased/Breaking Changes-20241016-184157.yaml
- .github/workflows/main.yml
- .pre-commit-config.yaml
- CONTRIBUTING.md
- Makefile
- setup.py
- tox.ini
> [Backport 1.6.latest] Drop support for Python 3.8

- .changes/unreleased/Breaking Changes-20241016-184157.yaml
- .github/workflows/main.yml
- .pre-commit-config.yaml
- CONTRIBUTING.md
- Makefile
- setup.py
- tox.ini
> [Backport 1.7.latest] Drop support for Python 3.8

- .github/workflows/main.yml
> move github runner from macos-12 to macos-14

- .github/workflows/main.yml
> move from macos-12 to macos-14 (#1136)
