dbt-labs/dbt-spark

setup.py
Closes #8 by changing the `setup.py` package_data path to match the actual path of the Spark dbt project.
=> fix spark dbt project path

README.md, dbt/adapters/spark/connections.py, dbt/adapters/spark/impl.py, dbt/include/spark/macros/adapters.sql
This PR: closes #10, closes #12, closes #13
- Add two profile configs, `connect_timeout` and `connect_retries` to handle slow startup time for interactive Spark clusters
- Support catalog generation (and therefore `dbt docs`)
- Code cleanup / remove debug lines / etc
Testing checklist:
Note: The docs site won't be perfect -- in javascript, we assume that databases will have both a schema and a database. Let's enumerate and updates we need to make for dbt Documentation on Spark in an issue against the dbt-docs repo
=> Handle interactive cluster startup, implement docs generation

dbt/include/spark/macros/materializations/table.sql, dbt/include/spark/macros/materializations/view.sql
Implement a _really_ simple table materialization for Spark that drops the existing table before creating.
From [Databricks docs](https://docs.databricks.com/spark/latest/spark-sql/language-manual/alter-table-or-view.html):
> For managed tables, renaming a table moves the table location; for unmanaged (external) tables, renaming a table does not move the table location.
In our experience, renaming the backup table takes as long as (or longer than) actual table creation. The [Databricks docs](https://docs.databricks.com/user-guide/tables.html#replace-table-contents) suggest two ways of replacing table contents: the simple way (this one) and the recommended way (using `insert overwrite`, which fails on schema changes).
* We _could_ implement non-destructive mode using `insert overwrite`, …
=> Naïve table materialization

README.md, dbt/adapters/spark/connections.py
Adding a method selector to the profile configuration, to toggle between `http` (existing behavior) and `thrift` (direct conneciton to cluster).
=> Adding `thrift` mode

dbt/include/spark/macros/materializations/incremental.sql
It would be nice to be able to override the default config set for incremental models:
`set spark.sql.hive.convertMetastoreParquet = false`
Currently, there is no way to do so. Running the prehooks after setting this configuration would allow to override it by doing the following:
```
{{ config(
materialized='incremental',
partition_by=['my_partition_key'],
file_format='parquet',
pre_hook=[
'set spark.sql.hive.convertMetastoreParquet = true'
]
) }}
```
=> Allow overriding hardcoded spark config in pre_hook

README.md
The formatting hid the most important part of the hostname.  And also formatting organization to match the rest of the table.
=> Clarifying Databricks hostname in readme

dbt/adapters/spark/connections.py, dbt/adapters/spark/impl.py
=> Reimplement get_relation to handle custom schemas

README.md, dbt/adapters/spark/impl.py, dbt/include/spark/macros/adapters.sql, test/unit/test_macros.py
Implemented Location and Clustered By options which were not exposed as options.
https://docs.databricks.com/spark/latest/spark-sql/language-manual/create-table.html
=> Expose location, clustered_by to dbt-spark

dbt/adapters/spark/impl.py, dbt/include/spark/macros/adapters.sql, dbt/include/spark/macros/materializations/incremental.sql
* Following #49, leverage `show table extended in ... like '*'` statement to get metadata on all relational objects in each database/schema, including their `Type`
* Naively check the `information` column result of the statement for the substring `'Type: VIEW'`. If found in the text result, set `relation.type` to `'view'`, otherwise set to `'table'`. (I am seeing `Type: MANAGED` for tables that dbt creates in Databricks.)
* Catch `Database ... not found` exception if dbt runs the statement for a database that doesn't (yet) exist. I encountered this error after creating a dbt model with a custom schema and executing a dbt commands which did not run that model (e.g. `dbt seed`).
* Fixes #48
=> Leverage "show table extended" for Relation type metadata

dbt/adapters/spark/impl.py
Describing the schema can fail (e.g. I have a table with no `StorageDescriptor#InputFormat`) causing the describe command to fail. (The table is created via the Glue Crawler on AWS).
We might just return no results in this case to be able to continue generating docs.
The error when running dbt docs generate:
```
show table extended in raw like '*'
2020-02-13 18:27:57,861 (MainThread): Database Error
org.apache.spark.sql.AnalysisException: org.apache.hadoop.hive.ql.metadata.HiveException: Unable to fetch table db_raw. StorageDescriptor#InputFormat cannot be null for table: db_raw (Service: null; Status Code: 0; Error Code: null; Request ID: null);
```
=> Return without results when list relations fails

dbt/include/spark/macros/materializations/incremental.sql
* Fixes #59
* Plays nicely with #39 (passing integration tests)
In #39, we change `spark__get_columns_in_relation` from `describe` to `describe extended`. Spark has the interesting behavior of including a table's partition column(s) _twice_ in the output, once among the set of columns and again in the `# Partition Information` section.
```
describe extended dbt_jcohen.incremental_relation
```
| col_name | data_type | comment |
| -- | -- | -- |
| first_name | string | null |
| last_name | string | null |
| email | string | null |
| gender | string | null |
| ip_address | string | null |
| id | bigint | null |
| # Partition Information |   |   |
| # col_name | data_type | comment |
| id | bigint | null |
|   |   |   |
| # Detailed Table Information |   |   |
| ... | ... | ... |
Thus, …
=> Fix: column order for incremental insert overwrite

dbt/adapters/spark/impl.py, dbt/adapters/spark/relation.py, test/unit/test_adapter.py, test/unit/test_macros.py
Depends on https://github.com/fishtown-analytics/dbt-spark/pull/39
With Spark you can compute statistics using `ANALYZE TABLE <table> COMPUTE STATISTICS`. This will compute statistics such as number of rows, and size and this will be stored in the metastore. With this PR this data will be fetched and shown in the docs:
=> Add support for extracting statistics

.circleci/config.yml
I would like to add `dockerize` to the main test image to avoid having to download it on each trigger of integration tests
Also made a minor cleanup: removed the unused "SPARK_HOST" variable
=> Use dockerize from test image

.gitignore, README.md, dbt/adapters/spark/__init__.py, dbt/adapters/spark/column.py, dbt/adapters/spark/connections.py, dbt/adapters/spark/impl.py, dbt/adapters/spark/relation.py, dbt/include/spark/macros/adapters.sql, dbt/include/spark/macros/materializations/incremental.sql, dbt/include/spark/macros/materializations/seed.sql, dbt/include/spark/macros/materializations/table.sql, dbt/include/spark/macros/materializations/view.sql, requirements.txt, setup.py, test/unit/test_adapter.py, test/unit/utils.py
**Additions/Fixes**
- Incorporated fixes from current pull requests (8)
- Added missing 0.15.0 functionality
- Databricks Delta compatibility
- incremental_strategy = `merge` (Databricks) or `insert_overwrite`
- Additional model config options: partition_by, cluster_by, num_buckets, location
- Cache schema and relations
- Updated README
dbt-integration-tests all pass. I haven't added many unit tests at this stage, so this is something to work on.
=> 0.15.0 upgrade

.bumpversion.cfg, dbt/adapters/spark/impl.py, dbt/include/spark/macros/adapters.sql, dbt/include/spark/macros/materializations/incremental.sql, setup.py
Fixes #67 
Upgrade `dbt-spark` to work with `dbt-core==0.16.0`
- remove duplicate macros (as of `dbt-core==0.16.0`, this is an error)
- use `get_merge_sql` from `dbt-core` instead of a custom one
- slightly loosen versioning restrictions between `dbt-core` and `dbt-spark`
- Fix the requirements to use `==` instead of `>==` (which becomes `>=`!)
- add bumpversion
=> upgrade to dbt-core==0.16.0

README.md
Tiny fix to formatting in Readme.md for the Usage Notes table. Barely seemed worth it so feel free to ignore, but I fixed it in my fork so that I could read the table and figured I might as well offer up the PR.
=> Table formatting of Usage Notes

README.md
* More concise overview of different Databricks profile configs
* Add `persist_docs` as optional model-level config (added in #43)
* Light touch-up to docs links, per https://github.com/fishtown-analytics/docs.getdbt.com/pull/77
=> Update readme (0.16.0)

dbt/adapters/spark/impl.py
Fixes #75 
I never updated catalog generation, but it changed in dbt 0.16.0. This PR fixes `dbt docs generate` by making use of dbt 0.16.0's parallel catalog generation.
I've also added running `dbt docs generate` to the spark integration testing branch.
=> fix catalog generation

.bumpversion-dbt.cfg, .bumpversion.cfg, dbt/adapters/spark/__version__.py, dbt/adapters/spark/connections.py, dbt/adapters/spark/impl.py, dbt/adapters/spark/relation.py, dbt/include/spark/dbt_project.yml, dbt/include/spark/macros/adapters.sql, requirements.txt, setup.py, test/unit/test_adapter.py, test/unit/utils.py
Fixes #78 
Fixes #81 (sort of...)
Prevent users from setting `database` just about anywhere. It would have been nice to make `database` and `schema` equivalent, like in real spark, but that requires some ugly hacks on the dbt-core end.
In the longer term, it would be nice to expose more things about `config` to plugins. Adapter specific configs can add new fields, but they can't remove them, and they can't even really check on them to see if they make sense because the builtin fields are examined before the adapter ones are considered. I'm not sure how exactly we could support such behavior in the dataclasses/hologram paradigm, but we can think about it more. Instead, the spark adapter now checks when relations are built, and errors out then. I don't think it's ideal, but it happens …
=> Upgrade to 0.17.0rc2

README.md, dbt/adapters/spark/impl.py
* Resolves #71
* Add a note to README about min required Spark version (we think 2.2.0). We could add a more codified version check/requirement, but since we don't have a _great_ sense of what all historical versions we do/don't support, I think a disclaimer is enough for now.
* Raise a better error message if `show table extended in database ... like '*'` returns fewer columns than expected (4). It seems to return 2 columns on older Spark versions (< 2.2.0).
=> Better messaging for older Spark versions

.bumpversion-dbt.cfg, .bumpversion.cfg, dbt/adapters/spark/__version__.py, dbt/adapters/spark/connections.py, dbt/adapters/spark/impl.py, dbt/adapters/spark/relation.py, dbt/include/spark/macros/adapters.sql, requirements.txt, setup.py, test/unit/test_adapter.py
resolves #85 
resolves #89 
resolves #90 
~Of course, 0.17.0rc3 doesn't exist yet, but it will soon, and it will fix these problems!~ 0.17.3 exists and this points to it now.
If it was resolved by https://github.com/fishtown-analytics/dbt/pull/2489, I marked it as resolved by this PR - peeling the consequences of the two apart sounds annoying.
This PR takes the opinionated stance that you aren't allowed to use `database` in spark, it's always None. There is probably room to go further (maybe `spark__generate_database_name` should raise if your `custom_database_name` is non-None), but I think this is functional.
- remove `_parse_relation` - it fully duplicates other code now.
- make use of dbt's `DEFAULT_TYPE_TESTER` for creating the agate table. This prevents an issue with `1` row …
=> Fix the catalog, making use of rc3 fixes

.bumpversion-dbt.cfg, .bumpversion.cfg, dbt/adapters/spark/__version__.py, dbt/adapters/spark/impl.py, requirements.txt, setup.py
Remove the `release` argument from `execute_macro`. Everything worked fine with or without it. While I left it in, I saw the deprecation warning:
```
* Deprecation Warning: The "release" argument to execute_macro is now ignored,
and will be removed in a future relase of dbt. At that time, providing a
`release` argument will result in an error.
```
Leaving as a draft until we release dbt v0.17.2.
=> Bump v0.17.2

dbt/include/spark/sample_profiles.yml, setup.py
resolves [#2533](https://github.com/fishtown-analytics/dbt/issues/2533)
Added option '--adapter' to `dbt init`, to create sample profiles.yml based on chosen adapter.
It gets the sample profiles.yml from the adapter 'includes' folder
=> Added sample_profiles.yml so that adapter works with new --adapter option of dbt init

.bumpversion-dbt.cfg, .bumpversion.cfg, dbt/adapters/spark/__version__.py, dbt/adapters/spark/impl.py, dbt/include/spark/macros/materializations/seed.sql, requirements.txt, setup.py, test/unit/utils.py
Bump dbt to 0.18.0rc1
Make a number of changes to support dbt-adapter-tests. A future PR will wire those up to this project (requires fishtown-analytics/dbt-adapter-tests/pull/3)
=> dbt 0.18.0 support

dbt/adapters/spark/connections.py, test/unit/test_adapter.py
Fixes https://github.com/fishtown-analytics/dbt-spark/issues/106
Allows users to specify auth and kerberos_service_name.  This won't impact existing users who upgrade.
=> allow kerberos

README.md, dbt/include/spark/macros/materializations/incremental.sql
**Problem:** 
Using incremental materialization with a insert_overwrite strategy without a unique_key doesn't work. 
```
{{
config(
materialized='incremental',
file_format='delta',
incremental_strategy='insert_overwrite'
)
}}
```
**Error message**  
Table charlotte.test does not support dynamic overwrite in batch mode.
**Fix**  
Relocating the "spark.sql.sources.partitionOverwriteMode = DYNAMIC" inside the merge strategy. Because this is only necessary when you give a unique_key, and for insert_overwrite this is not a must, but for merge it is.
=> replace partitionOverwriteMode inside merge strategy

.circleci/config.yml, .gitignore, README.md, dbt/adapters/spark/connections.py, dev_requirements.txt, requirements.txt, setup.py, test/integration/spark-databricks-http.dbtspec, test/integration/spark-databricks-odbc-cluster.dbtspec, test/integration/spark-databricks-odbc-sql-endpoint.dbtspec, test/integration/spark-databricks-odbc.dbtspec, test/integration/spark-thrift.dbtspec, test/unit/test_adapter.py, tox.ini
Resolves #104
Add support for ODBC driver connections with Databricks via cluster specific path and sql endpoint path.
- add `pyodbc` for using ODBC driver for connection
- add `driver` and `endpoint` to profile config (`cluster` and `endpoint` are mutually exclusive, they determine how to connect to Databricks)
- add integration and unit tests
- because this connection method uses a driver, I created a new image with the driver installed for integration tests to use. TBD where this Dockerfile lives!
At the time of writing this, the new SQL Endpoint does not support `create temporary view`. Also, `extended` is prohibited by the ODBC driver for some operations https://github.com/fishtown-analytics/dbt-adapter-tests/pull/8
=> Support for ODBC driver connection type

setup.py
resolves #122 
before:
```bash
pip install ".[ODBC]"
Processing /Users/kwigley/workspace/dbt-spark
WARNING: dbt-spark 0.18.1 does not provide the extra 'odbc'
```
after:
```bash
pip install ".[ODBC]"
Processing /Users/kwigley/workspace/dbt-spark
...
Successfully installed ... pyodbc-4.0.30 ...
```
=> Fix issue when installing pyodbc

CHANGELOG.md, dbt/adapters/spark/connections.py, setup.py
resolves #109 
- [`sasl`](https://github.com/cloudera/python-sasl) is an older package, not regularly maintained, and it's been bricking installs on a number of different systems
- It's a requirement of `PyHive[hive]`, which is used for `thrift` and `http` connection methods.
- If a user wants to use the `odbc` connection method, that doesn't require `PyHive` at all. Today, inability to install `sasl` prevents them from being able to use the plugin.
- This PR moves `PyHive` to be an extra requirement, rather than primary one
- Pro: easier for ODBC users
- Con: breaking change for existing users, who will need to replace `pip install dbt-spark` with `pip install dbt-spark[PyHive]`
- Neutral: moves `thrift` to be an extra as well, since it's only needed by the same connection types
=> Move PyHive requirement to extra

CHANGELOG.md, dbt/adapters/spark/connections.py
resolves #131
With a default of 0 connect_retries, confusing log messages show up. (see example below)
```bash
Running with dbt=0.18.1
Found 5 models, 12 tests, 0 snapshots, 0 analyses, 158 macros, 0 operations, 0 seed files, 3 sources
Warning: TEMPORARILY_UNAVAILABLE: Cluster <my-cluster-name> is temporarily unavailable. The current cluster state is Terminated. Please retry your request after 30 seconds.
Retrying in 10 seconds (0 of 0)
Encountered an error:
Runtime Error
Runtime Error
TEMPORARILY_UNAVAILABLE: Cluster <my-cluster-name> is temporarily unavailable. The current cluster state is Terminated. Please retry your request after 30 seconds.
```
We encountered this while working with Databricks, where we had a cluster that had not been started yet.
The logs suggest that a retry is …
=> Handle case of 0 connect retries better for HTTP Spark Connections

CHANGELOG.md, dbt/adapters/spark/column.py, dbt/adapters/spark/impl.py, dbt/adapters/spark/relation.py, dbt/include/spark/macros/adapters.sql, dbt/include/spark/macros/materializations/incremental.sql, dbt/include/spark/macros/materializations/snapshot.sql, dbt/include/spark/macros/materializations/table.sql, test/unit/test_macros.py
With Delta we can do an atomic operation to replace the current version of the table, with a new version using the create or replace syntax.
For delta, and only delta, we can use the `CREATE OR REPLACE` syntax to atomically replace the table. This will make sure that the table is still available all the time.
resolves #124
Ran the tests:
```
MacBook-Pro-van-Fokko:dbt-integration-tests fokkodriesprong$ ./bin/run-with-profile default
Test direct copying of source tables    # features/001_basic_materializations.feature
Test materialized='view' -- @1.1   ..........
Test materialized='table' -- @1.2   ..........
Test materialized='incremental' -- @1.3   ..........
Test re-materializing models as different types    # features/002_rematerialize_models.feature
Materialize as view (view) first, …
```
=> Enable create or replace sql syntax

test/integration/spark-databricks-odbc-sql-endpoint.dbtspec
Offers temporarily relief from #133 (does not resolve)
It seems that `set` statements no longer work on SQL Analytics endpoints, and we use them in the `incremental` materialization. We'll bring this up with our contacts at Databricks.
In the meantime, this PR _totally_ disables `test_base` within the `odbc-sql-endpoint` spec. We could override/reimplement it within the spec, to remove just the step where `swappable` is `materialized: incremental`, but I don't think it's worth it. As I see it, the main purpose of having a dedicated `odbc-sql-endpoint` spec is:
- testing, at the most basic level, the two novel components of this connection method (ODBC driver + SQL endpoint)
- declaring which `dbt-spark` functionality is not yet at parity
- ~I have run this code in development and it …
=> Disable test_dbt_base on odbc-sql-endpoint spec (for now)

CHANGELOG.md, dbt/include/spark/macros/materializations/snapshot.sql
Resolved #143
Alternative: We stop overriding the default merge macros. Databricks' implementation is strictly better because it lets us use `update *` + `insert *`, but the default ones should still work, and it would avoid situations like this one where we miss an upstream improvement.
=> Capture hard deleted records in snapshots

CHANGELOG.md, dbt/adapters/spark/column.py, dbt/adapters/spark/connections.py, dbt/adapters/spark/impl.py, test/unit/test_adapter.py
This PR updates dbt-spark to use new serialization API that is the result of using Mashumaro in dbt-core. It also addresses failing unit tests as a result of updated the dbt-core version to `0.19.1b2`
=> fix unit tests related to new serialization api

CHANGELOG.md, MANIFEST.in, setup.py
resolves issue with 0.19.0 distribution with missing incremental materializations (`dbt/include/spark/macros/materializations/incremental`)
Used a `MANIFEST.in` file to define what non-python files to include ([docs](https://packaging.python.org/guides/using-manifest-in/))
=> Include incremental materializations in package distribution

CHANGELOG.md, dbt/adapters/spark/impl.py, test/unit/test_adapter.py
resolves #158 
Having an integer table_owner causes problems with dbt docs generate, so we make sure to always cast this to a String.
=> Cast table_owner to str

CHANGELOG.md, dbt/adapters/spark/impl.py, dbt/adapters/spark/relation.py, test/unit/test_adapter.py, test/unit/test_column.py
Resolves https://github.com/fishtown-analytics/dbt-spark/issues/93
Use regular expressions to parse the information retrieved by `show table extended in [schema] like '*'`. In this way, it's no longer necessary to run `show tblproperties` and `describe extended`  on every single relation.
=> Parse information returned by list_relations_without_caching macro to speed up catalog generation

CHANGELOG.md, dbt/adapters/spark/connections.py
resolves #153
This allows you to both do:
```
default:
target: dev
outputs:
dev:
...
host: adb-8170469668123456.8.azuredatabricks.net
```
and:
```
default:
target: dev
outputs:
dev:
...
host: https://adb-8170469668123456.8.azuredatabricks.net
```
=> Make the https:// optional

CHANGELOG.md, dbt/adapters/spark/impl.py, dbt/include/spark/macros/adapters.sql, test/unit/test_macros.py
resolves #147 
Adds an option clause macro which allows for adding options to a table via the config:
```jinja
{{
config(
materialized='table',
file_format='jdbc',
options={
'dbtable': 'my_table',
'url': 'jdbc:sqlserver://${spark.serverName}:1433;databaseName=database;',
'user': '${spark.adminUsername}',
'password': '${spark.adminPassword}'
}
)
}}
```
Heavily inspired on #148. @friendofasquid : I went ahead, implemented a solution based on the examples you created, here to contribute back.
=> Add options clause to create table macro

CHANGELOG.md, README.md, dbt/include/spark/macros/adapters.sql
resolves #84
Adds support for column descriptions when its in Delta format and `persist_docs = {'columns': true}`
=> Support persist_docs for column descriptions

CHANGELOG.md, dbt/include/spark/macros/adapters.sql, dbt/include/spark/macros/materializations/seed.sql, dbt/include/spark/macros/materializations/table.sql, test/custom/base.py, test/custom/persist_docs/data/seed.csv, test/custom/persist_docs/data/seeds.yml, test/custom/persist_docs/models/my_fun_docs.md, test/custom/persist_docs/models/no_docs_model.sql, test/custom/persist_docs/models/schema.yml, test/custom/persist_docs/models/table_delta_model.sql, test/custom/persist_docs/models/table_parquet_model.sql, test/custom/persist_docs/models/view_model.sql, test/custom/persist_docs/test_persist_docs.py
follow up to #84, #170
Although #170 implemented `spark__alter_column_comment`, we were missing the needed call to the `persist_docs` macro itself in needed materializations, since relation-level docs are handled within the `create_x_as` macro DDL.
So this PR:
- Defined `spark__persist_docs`, to add column descriptions _only_
- Adds a call to `persist_docs` to the table + seed materializations. It's already in the snapshot materialization, and views cannot persist columns descriptions.
- Adds an integration test modeled off [the one here](https://github.com/fishtown-analytics/dbt/blob/develop/test/integration/060_persist_docs_tests/test_persist_docs.py). Key difference: column descriptions don't show up in `show table extended in ... like '*'`, so instead of pulling from `catalog.json`, …
=> Fix persist_docs for columns

CHANGELOG.md, dbt/adapters/spark/impl.py, dbt/include/spark/macros/materializations/incremental/strategies.sql, test/custom/incremental_strategies/data/expected_partial_upsert.csv, test/custom/incremental_strategies/models_delta/merge_update_columns.sql, test/custom/incremental_strategies/test_incremental_strategies.py
Resolves #183
~Cherry-pick onto `0.20.latest` after merging.~ It looks like we merged the version bump into `0.20.latest` but not into `master`. For simplicity, I'm going to rebase this PR onto `0.20.latest`. Then, after merging, let's merge the changes from `0.20.latest` into `master`—which, while we're at it, we may as well rename `main` or `develop`.
=> Add merge_update_columns config

CHANGELOG.md, dbt/adapters/spark/connections.py
When `pydobc` can not be imported and the user specifies this connection method, we raise an error that the `dbt-spark[ODBC]` should be installed. However, it can also be that the package is installed, but that it still can not be imported. Then, the ImportError details useful information, like some ODBC image can not be found, which is resolved with installing `unixodb-dev`.
=> Show more detailed feedback when pyodbc import fails

CHANGELOG.md, dbt/adapters/spark/connections.py
Allow passing through Cluster Configuration parameters via `profiles.yml` when using the `odbc` connection method.
This allows configuration of values that would need to be set via [SET](https://spark.apache.org/docs/3.0.0-preview/sql-ref-syntax-aux-conf-mgmt-set.html) to be run in the Spark session and take effect on DBT models.
E.g.:
```yaml
spark_dbt:
target: default
outputs:
default:
type: spark
method: odbc
driver: /opt/simba/spark/lib/64/libsparkodbc_sb64.so
schema: default
host: [hostid]
token: [token]
cluster: [clusterid]
port: 443
connect_retries: 3
connect_timeout: 20
server_side_parameters:
"spark.databricks.delta.schema.autoMerge.enabled": True
"spark.sql.jsonGenerator.ignoreNullFields": True
```
=> Add support for ODBC Server Side Parameters

CHANGELOG.md, dbt/adapters/spark/impl.py
resolves #199 
Enhanced get_columns_in_relation method to handle a bug in open source deltalake which doesnt return schema details in `show table extended in databasename like '*'` query output
=> fixed get_columns_in_relation for open source delta table

CHANGELOG.md, dbt/adapters/spark/impl.py, test/unit/test_adapter.py
resolves #202
The issue was when parsing the schema, the current regex deal with inner struct fields as root fields, hence causing an error later because the column was not found (check issue #202 for a more detailed description)
Current one: 
Proposed one:
=> fix issue parsing structs

CHANGELOG.md, dbt/adapters/spark/connections.py
Follow-up to https://github.com/dbt-labs/dbt/pull/3796
=> Add adapter unique_field

CHANGELOG.md, dbt/adapters/spark/connections.py, dbt/adapters/spark/impl.py, tests/integration/base.py
Updates to allow adapter to use new struct logger in dbt-core [#4176](https://github.com/dbt-labs/dbt-core/pull/4176)
=> convert to use struct logging for adapters

.bumpversion.cfg, CHANGELOG.md, dbt/adapters/spark/__version__.py
The equivalent GHA [failed on a dependency step](https://github.com/dbt-labs/dbt-spark/runs/4165250703?check_suite_focus=true), so it's Jeremy Actions for now
=> Bumping version to 1.0.0rc1

.bumpversion.cfg, CHANGELOG.md, dbt/adapters/spark/__version__.py, dev_requirements.txt
The automated workflow runs into dependency issues: https://github.com/dbt-labs/dbt-spark/actions/runs/1491887246. (I don't think we actually need all those dependencies in `dev_requirements.txt`.)
So, still me for now :)
=> Bump version to 1.0.0rc2

CHANGELOG.md, dbt/include/spark/macros/materializations/incremental/incremental.sql
resolves #260
The current definition of the file ```dbt-spark\dbt\include\spark\macros\materializations\incremental\incremental.sql``` has an errouneous implementation of ```set full_refresh_mode``` that does not take into consideration the definition that is set in the config.
This PR corrects this issue by replacing it with the implementation in dbt-core/dbt-snowflake/etc.
As this PR only brings dbt-spark in sync with the other repos, and it's only one line of code, I figured tests are not relevant for this PR.
=> Corrected definition for set full_refresh_mode

dbt/adapters/spark/connections.py
In `core.dbt.adapters.sql.connection`, we:
- Say that `get_response` is an abstract method which can return `Union[AdapterResponse, str]`
- Expect an `AdapterResponse` (an object with a `_message` attribute) when we fire [`SQLQueryStatus`](https://github.com/dbt-labs/dbt-core/blob/9ed9936c84ef5a2706ad15f9757fb83a9c14139b/core/dbt/adapters/sql/connections.py#L78), ever since https://github.com/dbt-labs/dbt-core/commit/b3039fdc7629b5027096e92ed9b7612419cf3fea
Before this change, `dbt-spark` implemented `get_response` in a super naive way (it just returns a string). This PR changes it to return an `AdapterResponse` instead, with no functional change.
In `dbt-core`, we should either:
- Check the type of the value returned by `get_response`, then either use it `_message` attribute (if …
=> `get_response` -> `AdapterResponse`

.github/workflows/release.yml
We removed `bumpversion-dbt.cfg` from the repo
=> Removing old bumpversion file reference from release

.bumpversion.cfg, dbt/adapters/spark/__version__.py, setup.py
Fixing up version bumping script to match the other adapters. Removed some unneeded logic and updated to be on `1.0.0`
=> Fixing version bumping issues

.github/workflows/jira-creation.yml, .github/workflows/jira-label.yml, .github/workflows/jira-transition.yml
This adds the Jira mirroring Actions to this repo. It takes advantage of the common Action created in this repo: https://github.com/dbt-labs/jira-actions/tree/main/.github/workflows
=> Adding Jira mirring Actions

dbt/adapters/spark/connections.py
Since our name change happened in June 2020, I wanted to update the user agent to reflect that. 
- [ x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
=> update user agent

CHANGELOG.md, dbt/adapters/spark/connections.py
This closes connections after use, fixing an issue whereby clusters may not auto-terminate after a dbt run completes, with significant cost implications.
I believe we ought to include this fix in a `dbt-spark==1.0.1` patch release. We can first cut v1.0.1-rc1, for testing locally + in dbt Cloud (will be automatically included in the `v1.0.x (PRERELEASE patch - fixes only)` runtime image). Since the PR was merged into `main`, it will already be available in `development (HEAD)` later today.
Details in https://github.com/dbt-labs/dbt-spark/issues/280
Mirrors the change in https://github.com/databricks/dbt-databricks/pull/37
=> [Backport] #285 to `1.0.latest`

CHANGELOG.md, dbt/include/spark/macros/adapters.sql, tests/unit/test_macros.py
resolves #319
Makes internal macros use macro dispatch to be overridable in child adapters.
The target macros are:
- `file_format_clause`
- `location_clause`
- `options_clause`
- `comment_clause`
- `partition_cols`
- `clustered_cols`
- `create_temporary_view`
=> Make internal macros use macro dispatch to be overridable in child adapters

.bumpversion.cfg, setup.py
This backport was missed #271 which caused the version bump script to miss a file. This is the backport plus the missed version bump
=> `1.0.1rc1` version bump miss

.circleci/config.yml, tests/conftest.py, tests/functional/adapter/test_basic.py, tests/integration/base.py, tox.ini
resolves #326
- Turn on `retry_all` for all connection methods in CI
- 3 retries, 5 seconds apart, for most connection methods
- 5 retries, 60 seconds apart, for `http` — this needs to handle downtime while cluster restarts, and that can take several minutes. As such, turn on `retry_all` in CI, but turn it off by default for local dev/testing. Better to have intermittent failures in dev than a 5 min delay.
- ~I have updated the `CHANGELOG.md` and added information about my change to the "dbt-spark next" section.~
=> CI ergonomics: connection retries

.gitignore, dev_requirements.txt
resolves # https://github.com/dbt-labs/dbt-spark/pull/307
Changing ref pointer for `dbt-core` install so branches test against correct "main" branch to have correct testing cases throughout history.
=> changing pointer for dbt-core in 1.0.latest

tests/conftest.py
resolves #351
This PR fixes some misnomers within a Python comment.
Related to https://github.com/dbt-labs/docs.getdbt.com/pull/1437
=> Fix misnomers within the comment

dbt/adapters/spark/impl.py, dbt/include/spark/macros/adapters.sql
Use dispatch pattern for `get_columns_in_relation_raw` macro that was introduced at #355 for adapters that inherits `dbt-spark` to override the macro.
=> Use dispatch pattern for get_columns_in_relation_raw macro

CHANGELOG.md, dbt/adapters/spark/connections.py
Companion PR: https://github.com/databricks/dbt-databricks/pull/106
- Add the `DBT_INVOCATION_ENV` environment variable to the user agent, per Databricks' request (cc @ueshin @bilalaslamseattle)
- ~This PR includes tests, or tests are not required/relevant for this PR~
=> Add invocation env to user agent string

tests/functional/adapter/utils/test_utils.py
Error from `TestDateDiff` on the `apache_spark` cluster:
```
ERROR    configured_file:functions.py:232 15:49:39.369957 [error] [MainThread]:     org.apache.hive.service.cli.HiveSQLException: Error running query: org.apache.spark.sql.AnalysisException: org.apache.hadoop.hive.ql.metadata.HiveException: MetaException(message:Insert of object "org.apache.hadoop.hive.metastore.model.MTable@445045d2" using statement "INSERT INTO TBLS (TBL_ID,CREATE_TIME,DB_ID,LAST_ACCESS_TIME,OWNER,RETENTION,IS_REWRITE_ENABLED,SD_ID,TBL_NAME,TBL_TYPE,VIEW_EXPANDED_TEXT,VIEW_ORIGINAL_TEXT) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)" failed : A truncation error was encountered trying to shrink LONG VARCHAR 'with data as (
ERROR    configured_std_out:functions.py:232 15:49:39 …
```
=> Disable TestDateDiff on apache_spark

CHANGELOG.md, dbt/adapters/spark/connections.py
#367 added an environment variable to server-side user-agent tracking. This was a mistake, for two reasons:
- We are moving to standardize and simplify the information that dbt supplies in user agents. This should be only **dbt**, or **dbt-{version}** where appropriate. The addition of this env var would make the user agent much less consistent.
- The environment variable I included is an internal mechanism, not a reliable external contract to which we've committed. It could change in the future without warning. It isn't the right way to share this contextual information.
=> Revert #367

CHANGELOG.md, dbt/adapters/spark/column.py, dev-requirements.txt, tests/functional/adapter/utils/test_data_types.py
See https://github.com/dbt-labs/dbt-core/pull/5428
=> Data type macros

CHANGELOG.md, requirements.txt
Pin pyodbc to a known-working version until pyodbc>=4.0.35 releases.
resolves #397 
Pin the pyodbc version to prevent a bad installation of libodbc.so and libltdl.s on linux distros.
=> [CT-868] Pin pyodbc in dbt-spark

.github/workflows/main.yml
This updates CI to run on using `python -m pip install` instead of just `pip install` which has started to break windows builds. You can read more about the issue here: https://stackoverflow.com/a/25749976
Also adding Python 3.10 to testing matrix and some timeouts
=> Updating CI pip and py10

.github/workflows/main.yml
This `pip` -> `python -m pip` swap was done in PR #404 but this spot was missed
=> Fixing one more pip reference in CI

CHANGELOG.md, requirements.txt
backporting  #398
Just double check this is how we want the changelog to look.
=> [backport] pyodbc version pin

tests/conftest.py, tests/functional/adapter/test_python_model.py
This PR will enable running python model tests for `databricks_cluster` and `databricks_http_cluster` connection methods in Circle CI, we added new env var `DBT_DATABRICKS_USER` to support it
=> enable python model test

.github/workflows/backport.yml, .github/workflows/version-bump.yml
resolves #427 
Updates version bump to also generate changelog, uses centralized reusable workflow that all adapters (and eventually core) can also use.
Adds backport action now that changie is implemented.
=> Shared version-bump and adding backport actions

.changes/unreleased/Under the Hood-20220829-164426.yaml, dbt/adapters/spark/impl.py, dbt/adapters/spark/python_submissions.py
resolves #424 #419
Use Command API as default python model submission method. User can still create the notebook by adding `submission_method:'notebook'` in config for the model
=> refactor submission method and add command API as defualt

.changes/unreleased/Fixes-20220830-140224.yaml, dbt/include/spark/macros/adapters.sql, dbt/include/spark/macros/materializations/incremental/incremental.sql, dbt/include/spark/macros/materializations/incremental/strategies.sql
resolves #441 
Creating tmp relation with correct schema and database for both python and sql model upfront. Remove logic to handle relation in merge sql macros.
=> set tmp relation with proper schema

.changes/unreleased/Features-20220923-101248.yaml, dbt/adapters/spark/connections.py, dbt/adapters/spark/impl.py, dbt/adapters/spark/python_submissions.py, tests/functional/adapter/test_python_model.py
resolves #444 
When using notebook submission, if `job_cluster_config` is specified, we will run that model with a job_cluster.
This PR also makes user being able to specify a separate `cluster_id` or `job_cluster_config` for each individual model through config. 
`job_cluster_config` will overwrite `cluster_id` in current situation.(if `job_cluster_config` is set for a model, we will always use it).
This PR also removes the need for `user` and put dbt model files under `/dbt_python_mode/{$SCHEMA}` in Databricks workspace
=> More flexible cluster configuration

dbt/include/spark/macros/materializations/table.sql
resolves #326
Uses the implementation [here](https://github.com/databricks/dbt-databricks/pull/196) by @ueshin.
There is a discussion [here](https://github.com/dbt-labs/dbt-spark/pull/474#discussion_r982414507) about how we could choose to optimize import load times in the future.
Choosing to ["make it right"](https://wiki.c2.com/?MakeItWorkMakeItRightMakeItFast) in this PR rather than ["make it fast"](https://wiki.c2.com/?MakeItWorkMakeItRightMakeItFast). (The performance cost for importing `pandas` was only ~1 second in local testing.)
- ⚠️ It would be great if we could add different test environments that do/don't have each of these libraries installed. In the meantime, we are just manually testing against environments that _do_ have them all available.
=> try/except rather than find_spec for optional imports

.pre-commit-config.yaml
resolves: [Flake8 took down the gitlab repository in favor of github](https://www.reddit.com/r/Python/comments/yvfww8/flake8_took_down_the_gitlab_repository_in_favor/)
Updating to [documented](https://flake8.pycqa.org/en/latest/user/using-hooks.html#usage-with-the-pre-commit-git-hooks-framework) github flake8 repo: https://github.com/pycqa/flake8.
=> Spark Implementation of flake8 fix to swap gitlab for github

.github/workflows/main.yml, tests/functional/adapter/test_basic.py
resolves #403 
backporting changes to pip install for gha to 1.1.latest
also incorporates changes from #405 and  #359 (skip of test that is failing in run)
todo:
- do we need to also backport a version of this to 1.0?
=> [BACKPORT] #403 to 1.1.latest

.changes/unreleased/Fixes-20221116-234601.yaml, dbt/adapters/spark/impl.py
resolves #515
Supports new error messages.
In `SparkAdapter.get_columns_in_relation`, it checks the error message when the specified table or view doesn't exist:
https://github.com/dbt-labs/dbt-spark/blob/c87b6b2c48bcefb0ce52cd64984d3129d6f14ea0/dbt/adapters/spark/impl.py#L223
but, Spark will change the error message in the future release (https://github.com/apache/spark/pull/37887), which causes the function to raise the `dbt.exceptions.RuntimeException` instead of returning an empty list.
The function should also check whether the error message contains `[TABLE_OR_VIEW_NOT_FOUND]` or not.
=> Supports new error messages.

.changes/unreleased/Under the Hood-20221202-140724.yaml, CONTRIBUTING.md, setup.py, tox.ini
resolves #536
errors in workflow caused by old python version
=> trying to fix tox issue causing failures

.changes/unreleased/Under the Hood-20221209-143821.yaml, tox.ini
…senv spacing
resolves #
updating 1.2.latest tox.ini file for post tox 4.0.0 release use
changing how `passenv` now has to have each variable on seperate line and adding `allowlist_externals` to allow for use of bash
=> [BACKPORT] adding allowlist_externals for bash script to tox tests, changing passenv

.github/workflows/release.yml
Adds PyPi into release automation.  When `test_run` is true, it will not release to PyPi.  Test PyPi releases will be added at a future date.
=> add pypi release to workflow

.changes/unreleased/Under the Hood-20230105-182038.yaml, .circleci/config.yml, tox.ini
resolves #581
Use a [CircleCI Context](https://circleci.com/docs/contexts/) for AWS access key environment variables.
The names of contexts within CircleCI are chosen by the user, and they act like a named group of environment variables that can be "imported" within `workflows` so that the individual environment variables can be used within `jobs`.
In this case, we know that the name we gave this context is `aws-credentials`, and we can look it up here:
https://app.circleci.com/settings/organization/github/dbt-labs/contexts
=> Use CircleCI Context for AWS access key environment variables

Makefile
`make dev` doesn't install everything you need to run tests today. this aims to fix that.
=> make dev installs requirements.txt too

.changie.yaml, .github/workflows/bot-changelog.yml
resolves #548 
Removes PR requirement from changelog and allows multiple issues to be listed for a single changelog.
=> Remove PR requirement from Changelog

.changie.yaml
resolves https://github.com/dbt-labs/dbt-spark/issues/548, extension of https://github.com/dbt-labs/dbt-spark/pull/603
Extensive testing surfaced another bug in all repos where contributors with multiple issues on a single changelog were not generating properly as separate issues.  This has not surfaced because generally it's just core group members that have a changelog entry with multiple issues and they never show up in the contributors section.
=> fix bug with contributor list

.changie.yaml, .github/workflows/bot-changelog.yml
Backport https://github.com/dbt-labs/dbt-spark/pull/620
Necessary to allow other back ports to work without conflicts. Since PR is no longer required on main, when a change is back ported it will not have the PR in the changelog yaml and will break changelog generation.
=> [BACKPORT] Remove PR requirement from Changelog

.github/workflows/release.yml
The release currently fails because IT_TEAM_MEMBERSHIP secret is not being passed in to the release-prep workflow.  This was an oversight in a previous update to add core team automation because while the release-prep workflow defines the secret, dbt-spark doesn't actually _use_ the secret right now.  This is because `dbt-spark` is still on CircleCI and so the release-prep workflow just makes sure the version is already bumped and changelog exists.  It does not trigger the version bump and changelog generation itself.
=> add release prep secret

.changes/unreleased/Features-20230223-180923.yaml, dbt/include/spark/macros/adapters.sql, dev-requirements.txt, tests/functional/adapter/test_constraints.py
resolves #654 
Support contracts for view materializations.
=> support contracts on models materialized as view

.changes/1.5.0/Under the Hood-20230223-105838.yaml, .changes/unreleased/Under the Hood-20230223-105838.yaml, dbt/include/spark/macros/adapters.sql, dev-requirements.txt
resolves #693 
contract config is now an object in `dbt-core` https://github.com/dbt-labs/dbt-core/pull/7222
=> update to retrieve contract enforced from dict

.changes/unreleased/Fixes-20230420-214433.yaml, dbt/include/spark/macros/materializations/table.sql
resolves #725 
We were not properly dropping an existing table relation when that model was refreshed using a non-admin account in Databricks. That prevented us from refreshing those models, as the non-admin account could not see the already existing tables, hence could not overwrite them. The original workaround was to elevate the service account to be an admin, but this was deemed too steep of a requirement. The solution that worked in the end was to update the table materialization itself, and drop the `target_relation` instead of the `old_relation`.
=> ADAP-473: Table materialization not properly dropping existing relation on refresh

.changes/unreleased/Dependencies-20230421-041623.yaml, .changes/unreleased/Dependencies-20230421-041627.yaml, dev-requirements.txt
Upgrade `pytest` to `~=7.3` to align with other adapters and dependabot.
=> Update pytest requirement from ~=7.2 to ~=7.3

.changes/unreleased/Under the Hood-20230508-222118.yaml, .pre-commit-config.yaml, dbt/adapters/spark/__init__.py, dbt/adapters/spark/impl.py
=> Remove unused `# type: ignore`

.changes/unreleased/Fixes-20230510-154735.yaml, dbt/adapters/spark/impl.py
Resolves #758 Less code is more!
=> Remove dead code 💀

.github/workflows/main.yml
resolves #740 
Backport to 1.4.latest. Does not require a patch release since this is only around testing automation.
=> [Backport] 1.4.latest gh deprecations

.changes/unreleased/Under the Hood-20230530-162533.yaml, .github/workflows/main.yml, CONTRIBUTING.md, dev-requirements.txt, setup.py, tox.ini
=> drop support for python 3.7

.changes/unreleased/Features-20230604-043421.yaml, dbt/adapters/spark/connections.py, dbt/adapters/spark/impl.py, tests/functional/adapter/utils/test_utils.py
PR to bring adapter in parity with [this core PR](https://github.com/dbt-labs/dbt-core/pull/7741).
I confirmed this `debug_query` does work. But, `_connection_keys` does not. I think we need to filter what params make it to the connection phase in core. That requires further scoping. After this is merged, I'll make a followup option.
=> Standardize the adapter for core debug changes

tests/functional/adapter/test_constraints.py
backports https://github.com/dbt-labs/dbt-spark/pull/798 to 1.5.latest
=> backport 798 to 1.5.latest

tests/unit/utils.py
=> add dependent_projects_dict to utils.py

.changes/unreleased/Fixes-20230623-112100.yaml, dbt/adapters/spark/connections.py
resolves #302
Allow hostname to be provided with or without trailing slash
When you copy in the hostname, it may or may not include trailing `/`
We could avoid confusion by allowing users to include or exclude these elements.
Before this change, `dbt debug` would get you something like this:
```
dbt was unable to connect to the specified database.
The database returned the following error:
>Runtime Error
Database Error
failed to connect
```
Output while using a trailing slash after change (given credentials are correct):
```
Connection test: [OK connection ok]
```
=> Allow hostname to be provided with or without a trailing slash

.changes/unreleased/Fixes-20230628-162413.yaml, tests/unit/utils.py
resolves #https://github.com/dbt-labs/dbt-core/pull/7955
=> Remove dependent_projects argument from PartialProject call in unit tests

.changes/unreleased/Features-20230627-155913.yaml, dbt/include/spark/macros/materializations/clone.sql, dev-requirements.txt, tests/functional/adapter/dbt_clone/fixtures.py, tests/functional/adapter/dbt_clone/test_dbt_clone.py
resolves #815 
adding the macros, and customer materialization needed on adapter side for dbt_clone and trying to design adapter zone version of Clone tests from defer_state in https://github.com/dbt-labs/dbt-core/pull/7881
=> dbt_clone macros, materialization and tests to dbt-spark

.circleci/config.yml, dev-requirements.txt, tox.ini
resolves #8081 
~~[docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose) dbt-labs/docs.getdbt.com/#~~ n/a
Datadog not ingesting test data for flaky test visibility
Adds env vars to turn on test visibility in datadog.  [Datadog docs](https://docs.datadoghq.com/continuous_integration/tests/python/?tab=cloudciprovideragentless#compatibility)
Updates the tox command to include the `--ddtrace` flag only when running in CI.
Update CircleCI: https://docs.datadoghq.com/continuous_integration/pipelines/circleci/
=> add datadog env vars

.github/workflows/bot-changelog.yml
The template is missing a new line at the end.
The template is no longer missing a new line at the end.
=> Add new line at the end of the dependabot changie to pass linter

.changes/unreleased/Fixes-20230810-014122.yaml, dbt/include/spark/macros/adapters.sql, dbt/include/spark/macros/materializations/seed.sql
resolves #
`tblproperties` clause macro is not used when creating tables. Add macro to adaptor.sql  
Add macro 
- [ x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x ] I have run this code in development and it appears to resolve the stated issue
=> Update adaptors.sql to use `tblproperties` macro

.changes/unreleased/Features-20231011-094718.yaml, dbt/include/spark/macros/adapters.sql
Taking over #902 to add changie/formatting fixes
resolves #350 
=> Create temporary views with 'or replace'

.changes/unreleased/Fixes-20231107-134141.yaml, dbt/adapters/spark/impl.py, dev-requirements.txt, tests/functional/adapter/test_simple_seed.py
resolves #935
dbt Core added support for an agate integer type to support the show command. Empty seeds were failing due to lack of support in the "convert_" methods in impl.py, so a regression bug case fixed that.
Add a "convert_integer_type" method and include test of empty seed creation.
=> Support new agate Integer type and test with empty seed

.changes/unreleased/Under the Hood-20231119-132050.yaml, dev-requirements.txt, tests/functional/adapter/empty/test_empty.py
resolves https://github.com/dbt-labs/dbt-spark/issues/949
[docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose) dbt-labs/docs.getdbt.com/# N/A
https://github.com/dbt-labs/dbt-core/pull/8971 introduced a new `--empty` flag that required implementation changes to the BaseRelation.
Add tests in dbt-bigquery to ensure expected behaviour of the new `--empty` flag when running with dbt-redshift.
=> add tests for --empty flag

.changes/unreleased/Under the Hood-20231214-134728.yaml, dbt/include/spark/macros/materializations/incremental/validate.sql
resolves #962
While researching https://github.com/dbt-labs/docs.getdbt.com/issues/4639, it looks like [this code](https://github.com/dbt-labs/dbt-spark/blob/ffc24ba30aa87e38e42ced897ccb19961425ad81/dbt/include/spark/macros/materializations/incremental/validate.sql#L32-L36) is unused since https://github.com/dbt-labs/dbt-spark/pull/700.
Searching both dbt-spark and dbt-databricks didn't yield any other references to `invalid_insert_overwrite_delta_msg`:
- https://github.com/search?q=repo%3Adbt-labs%2Fdbt-spark%20invalid_insert_overwrite_delta_msg&type=code
- https://github.com/search?q=repo%3Adatabricks%2Fdbt-databricks%20invalid_insert_overwrite_delta_msg&type=code
So it appears safe to remove it altogether.
=> Remove unused `invalid_insert_overwrite_delta_msg` variable

.changes/unreleased/Fixes-20231221-081949.yaml, dbt/include/spark/macros/materializations/table.sql
resolves #803 
Solves the bug in #803 
Maintains `delta` as the default `file_format`
=> Fix hardcoded file format in python materializations

dagger/run_dbt_spark_tests.py, dev-requirements.txt, tests/functional/conftest.py
=> fix spark cluster start mechanism and add extra dev requirements

.changes/unreleased/Features-20240220-195925.yaml, dbt/include/spark/macros/adapters.sql, dbt/include/spark/macros/utils/safe_cast.sql, dev-requirements.txt, tests/functional/adapter/unit_testing/test_unit_testing.py
resolves #https://github.com/dbt-labs/dbt-spark/issues/987
=> Add functional tests for unit testing

setup.py
We are pinning `dbt-adapters` with only final releases, which causes `pip` to skip all pre-releases for `dbt-adapters`.
Include a lower bound using the first pre-release on PyPI, which will allows installation of pre-releases, such as `1.0.0b1`.
=> Include a pre-release in the dbt-adapters pin to allow pre-releases to be installed on main

tox.ini
=> add tox file so release workflows succeed

.changes/unreleased/Features-20240318-033621.yaml, .github/workflows/release-internal.yml
resolves 38 of epic
This PR adds a workflow file for bigquery testing. It is based on https://github.com/dbt-labs/dbt-redshift/pull/732. I assume there will be some quirks to work out. Also, we'll need to add aws secrets.
=> Add workflow for spark and changelog

dagger/requirements.txt
resolves https://github.com/dbt-labs/adapters-team-private/issues/120
`dagger` has a regression due to `beartype`.
Pin `beartype<0.18.0` for now, until `dagger` does the same and publishes.
=> Pin `beartype<0.18.0`

.changes/unreleased/Dependencies-20240403-135436.yaml, setup.py
We need to preserve backwards compatibility for installing this package.
Include `dbt-core` as a dependency for installation, but do not depend on it within functional code.
=> Add `dbt-core~=1.8.0a1` as convenience dep

.pre-commit-config.yaml
See https://github.com/dbt-labs/dbt-adapters/issues/144
=> Add pre-commit check for dbt-core

.github/workflows/main.yml
`macos-latest` now points to `macos-14-arm64`; it used to point to `macos-12`. There is no `py39` nor `py38` on `macos-14-arm64`.
Pin to `macos-12` for now and discuss long term options to use `macos-14-arm64`, and CI pinning in general.
=> Pin `macos` test runners to `macos-12`

.github/workflows/main.yml
=> [Backport 1.2.latest] Pin `macos` runners to `macos-12` (#1016)

.github/workflows/main.yml
=> [Backport 1.1.latest] Pin `macos` runners to `macos-12` (#1016)

.github/workflows/main.yml
=> [Backport 1.7.latest] Pin `macos` runners to `macos-12` (#1016)

.github/workflows/main.yml
=> [Backport 1.6.latest] Pin `macos` runners to `macos-12` (#1016)

.github/workflows/main.yml
=> [Backport 1.5.latest] Pin `macos` runners to `macos-12` (#1016)

.github/workflows/main.yml
=> [Backport 1.4.latest] Pin `macos` runners to `macos-12` (#1016)

.github/workflows/main.yml
=> [Backport 1.3.latest] Pin `macos` runners to `macos-12` (#1016)

tests/functional/adapter/test_constraints.py, tests/functional/adapter/test_python_model.py
Two tests are consistently failing on `main`, which prevents CI from completing.
- create an issue for each test
- #1009
- #1033
- skip the test
- reference the issue in the skip
- resolve the failed tests according to priority
=> Skip tests on `main` to unblock CI, create issues to fix them

requirements.txt, test.env.example, tests/functional/adapter/test_constraints.py
resolves #1009
This test started failing. We skipped it to release and need to address the failure. We suspect there was a change with delta tables in Databricks that we're not properly accounting for.
- unskip the test
- update expected error messages to allow for ubuntu and macos versions
=> [Bug] Fix constraints enforcement rollover test

.changes/unreleased/Fixes-20240513-160121.yaml, dbt/include/spark/macros/adapters.sql, dbt/include/spark/macros/materializations/incremental/incremental.sql, requirements.txt, tests/functional/adapter/test_python_model.py
resolves #1033
This test started failing. We skipped it to release and need to address the failure.
- unskip test
- vendor `spark__make_temp_relation` logic into incremental materialization
=> [Bug] Fix incremental python tables - dbt can't find temporary table transaction logs

.changes/unreleased/Under the Hood-20240612-195629.yaml, dbt/adapters/spark/impl.py
resolves #1049
Let's lazy load Agate and make it available for type checking.
Propagates the lazy load paradigm from other adapter PRs.
=> Adap 1049/lazy load agate

tests/functional/adapter/test_python_model.py
resolves #1054
Two tests are broken due to dependencies in the Databricks cluster.
Skip them for now and link to the resolution issue.
=> skip broken tests, link to the issue for resolution

.github/workflows/docs-issues.yml, dev-requirements.txt
https://github.com/dbt-labs/adapters-team-private/issues/143
We want to make sure all adapters have a docs-issue workflow and if it exists currently make sure it is in the same state as the dbt-core workflow to where we trigger off issues now for parity.
=> update user docs-issue workflow

.github/workflows/release-internal.yml
=> update spark internal-release workflow

tests/functional/adapter/test_python_model.py
resolves #1054
- we're using an old runtime version of Spark for some tests
- there's an issue in `spacy` that requires `pydanic>=1.10.8` (see https://github.com/explosion/spaCy/issues/12659)
- there's an issue in `databricks.koalas` that requires an update in handling `numpy` updates; however, this library is no longer supported 
- update the version in the tests
- update `pydanic<1.10.3` to `pydanic>=1.10.8`
- add a docstring explaining all of this
- exclude the koalas test
=> Update the spark version to the current version

dev-requirements.txt
We don't use these test dependencies even though we declare them.
Remove them.
=> Remove unused test dependencies

.changes/unreleased/Features-20240903-161003.yaml, dbt/include/spark/macros/materializations/snapshot.sql, dev-requirements.txt, setup.py
resolves #1096
Support for https://github.com/dbt-labs/dbt-core/pull/10608, configuring snapshot column names
Modify snapshot.sql to support changed column names.
=> Allow configuring snapshot column names

.changes/unreleased/Features-20240925-125242.yaml, CONTRIBUTING.md, dagger/run_dbt_spark_tests.py, dbt/include/spark/macros/materializations/incremental/incremental.sql, dbt/include/spark/macros/materializations/incremental/strategies.sql, dbt/include/spark/macros/materializations/incremental/validate.sql, tests/functional/adapter/incremental_strategies/test_microbatch.py
resolves #1109
As part of https://github.com/dbt-labs/dbt-core/issues/10624, dbt-spark needs to implement a microbatch incremental strategy.
* In spark, this will use the insert_overwrite strategy and explicitly require a partition_by field.
* testing against same profiles as insert_overwrite testing
* testing against parquet, since it supports timestamp partitioning
=> Microbatch Strategy

.changes/unreleased/Features-20240927-133927.yaml, dbt/include/spark/macros/materializations/snapshot.sql, tests/functional/adapter/persist_docs/test_persist_docs.py, tests/functional/adapter/test_python_model.py
resolves #1112
Support work being done in dbt-core and dbt-adapters to enable setting the value of a current row in the dbt_valid_to column.
Support dbt-core https://github.com/dbt-core/issue/10187, dbt-adapters https://github.com/dbt-labs/dbt-adapters/pull/321.
Use the "dbt_valid_to_current" config.
=> Enable setting dbt_valid_to snapshot column to new setting dbt_valid_to_current

.changes/unreleased/Breaking Changes-20241016-184157.yaml, .github/workflows/main.yml, .github/workflows/release-internal.yml, .github/workflows/release-prep.yml, .pre-commit-config.yaml, Makefile, dagger/run_dbt_spark_tests.py, dev-requirements.txt, docker/Dockerfile, setup.py
Python 3.8 reached end of life on 10/7/2024.
Drop support for Python 3.8. Update tests to no longer run on Python 3.8.
=> Drop support for Python 3.8

.changes/unreleased/Breaking Changes-20241016-184157.yaml, .github/workflows/main.yml, .github/workflows/release-internal.yml, .github/workflows/release-prep.yml, .pre-commit-config.yaml, dagger/run_dbt_spark_tests.py, setup.py
=> [Backport 1.8.latest] Drop support for Python 3.8

setup.py, tests/functional/adapter/test_python_model.py
=> [Backport 1.8.latest] Update the spark version to the current version (#1055)

.github/workflows/main.yml
The `macos-12` runner is deprecated. `macos-14` is now `macos-latest`.
Upgrade to `macos-14` for our runners.
=> move github runner from macos-12 to macos-14

.github/workflows/release.yml
=> Add version bump into release.yml

.github/workflows/main.yml, dbt/adapters/spark/impl.py, tests/unit/test_adapter_telemetry.py
Backport dbt-labs/dbt-adapters#517 to `1.9.latest`
=> ADAP-1166: Add table format telemetry reporting to Spark adapter (#517)
